


#ifndef DIO_H_
#define DIO_H_
/*OPTIONS FOR SELECTING THE NUMBER OF PORTS FOR THE MICRO CONTROLLER
OPTIONS:
'1'FOR PORTA ONLY
'2'FOR PORTA AND PORTB
'3'FOR PORTA,PORTB AND PORTC
'4'FOR PORTA,PORTB,PORTC AND PORTD
*/
#define NUM_OF_PORTS     2
/************************************************************************/ 
/*DIO PIN DIRECTION CONFIGURATION OPTIONS*/
#define DIO_U8PININPUTWITHINTERNALPULLUP     0
#define DIO_U8PININPUTWITHEXTERNALPULLDOWN   1
#define DIO_U8PINOUTPUT                      2


/*DIO PIN VALUE OPTIONS*/
#define DIO_U8PINSTATELOW     0
#define DIO_U8PINSTATEHIGH    1

/*DIO PORT NUMBER OPTIONS*/
#define DIO_U8PORTA      1
#define DIO_U8PORTB      2
#define DIO_U8PORTC      3
#define DIO_U8PORTD      4

/*DIO PIN NUMBER OPTIONS*/
#define DIO_U8PIN0       0
#define DIO_U8PIN1       1
#define DIO_U8PIN2       2
#define DIO_U8PIN3       3
#define DIO_U8PIN4       4
#define DIO_U8PIN5       5
#define DIO_U8PIN6       6
#define DIO_U8PIN7       7


/*DIO PORT VALUE OPTIONS*/

#define DIO_U8PORT_HIGH  0xFF
#define DIO_U8PORT_LOW   0
/* ENUM FOR DEFINING ALL THE ERRORS THAT MIGHT COME FROM ANY FUNCTION IN THIS MODULE OPTIONS:
 0:IF ALL THE PARAMETERS ARE VALID AND NO WRONG PARAMETER SO THE FUNCTION BEHAVES WELL AND RETURNS 0.
 
 1:IF WE PASS POINTER TO VARIABLE THAT HOLDS NULL AND DOESN'T POINT TO ANY THING SO THE FUNCTION MAKES 
 UNDEFINED BEHAVIOUR AND RETURNS 1.
 
 2:IF WE PASS PORT NUMBER TO A FUNCTION THAT HOLDS A VALUE OUT OF THE RANGE FROM 0 TO 3 WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 2.
 
 3:IF WE PASS PIN NUMBER TO A FUNCTION THAT HOLDS A VALUE OUT OF THE RANGE FROM 0 TO 7 WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 3.
 
 4:IF WE PASS PIN DIRECTION TO A FUNCTION THAT HOLDS A VALUE NOT 0 NOR 1 WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 4.
 
 5:IF WE PASS PORT DIRECTION TO A FUNCTION THAT HOLDS A VALUE NOT IN THE RANGE FROM 0x0 TO 0xFF WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 5.
 
 6:IF WE PASS PIN VALUE TO A FUNCTION THAT HOLDS A VALUE NOT 0 NOR 1 WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 6.
 
 7:IF WE PASS PORT VALUE TO A FUNCTION THAT HOLDS A VALUE NOT IN THE RANGE FROM 0x0 TO 0xFF WHICH IS INVALID
 SO THE FUNCTION MAKES UNDEFINED BEHAVIOUR AND RETURNS 7.
 */
typedef enum{
	RetErrorState_OK=0,
	RetErrorState_NOK_NULLPTR,
	RetErrorState_NOK_WRONGPORTNUMBER,
	RetErrorState_NOK_WRONGPINNUMBER,
	RetErrorState_NOK_WRONGPINDIRECTION,
	RetErrorState_NOK_WRONGPORTDIRECTION,
	RetErrorState_NOK_WRONGPINVALUE,
	RetErrorState_NOK_WRONGPORTVALUE

}DIO_enumRetErrorState_t;
/******************************************************************************************************************/

/*FUNCTION FOR SETTING THE PIN CONFIGURATION IT TAKES 3 ARGUMENTS:THE PORT NUMBER FROM 0 TO 3,PIN 
NUMBER FROM 0 TO 7 AND THE PIN DIRECTION FROM 0 TO 2 AND RETURNS THE ERROR STATUS EITHER WRONG PORT 
NUMBER OR WRONG PIN NUMBER OR WRONG PIN DIRECTION OR EVERY THING IS OK AND SETTING THE PIN CONFIGURATION 
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/
DIO_enumRetErrorState_t DIO_enumSetPinDirection(u8 Copy_u8PortNumber,u8 Copy_u8PinNumber,u8 Copy_u8PinDirection);
/******************************************************************************************************************/

/*FUNCTION FOR SETTING THE PORT DIRECTION IT TAKES 2 ARGUMENTS:THE PORT NUMBER FROM
0 TO 3 AND THE PORT DIRECTION FROM 0x0 TO 0xFF AND RETURNS THE ERROR STATUS EITHER 
WRONG PORT NUMBER OR WRONG PORT DIRECTION OR EVERY THING IS OK AND SETTING THE PORT DIRECTION
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/

DIO_enumRetErrorState_t DIO_enumSetPortDirection(u8 Copy_u8PortNumber,u8 Copy_u8PortDirection);
/******************************************************************************************************************/

/*FUNCTION FOR SETTING THE PIN VALUE IT TAKES 3 ARGUMENTS:THE PORT NUMBER FROM 0 TO 3,PIN 
NUMBER FROM 0 TO 7 AND THE PIN VALUE EITHER 0 OR 1 AND RETURNS THE ERROR STATUS EITHER WRONG 
PORT NUMBER OR WRONG PIN NUMBER OR WRONG PIN VALUE OR EVERY THING IS OK AND SETTING THE PIN VALUE
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/

DIO_enumRetErrorState_t DIO_enumSetPinValue(u8 Copy_u8PortNumber,u8 Copy_u8PinNumber,u8 Copy_u8PinValue);
/******************************************************************************************************************/

/*FUNCTION FOR SETTING THE PORT VALUE IT TAKES 2 ARGUMENTS:THE PORT NUMBER FROM
0 TO 3 AND THE PORT VALUE FROM 0x0 TO 0xFF AND RETURNS THE ERROR STATUS EITHER 
WRONG PORT NUMBER OR WRONG PORT VALUE OR EVERY THING IS OK AND SETTING THE PORT VALUE
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/

DIO_enumRetErrorState_t DIO_enumSetPortValue(u8 Copy_u8PortNumber,u8 Copy_u8PortValue);
/******************************************************************************************************************/

/*FUNCTION FOR GETTING THE PIN VALUE IT TAKES 3 ARGUMENTS:THE PORT NUMBER FROM 0 TO 3,PIN NUMBER FROM
0 TO 7 AND POINTER TO VARIABLE THAT WILL HOLD THE VALUE OF THE PIN EITHER 0 OR 1 AND RETURNS THE ERROR
STATUS EITHER WRONG PORT NUMBER OR WRONG PIN NUMBER OR PASSING NULL POINTER AS AN ARGUMENT OR EVERY 
THING IS OK AND ASSIGNING THE PIN VALUE TO THE VARIABLE THAT WE HAVE PASSED
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/

DIO_enumRetErrorState_t DIO_enumGetPinValue(u8 Copy_u8PortNumber,u8 Copy_u8PinNumber,u8 *Copy_pu8PinValue);
/******************************************************************************************************************/

/*FUNCTION FOR GETTING THE PORT VALUE IT TAKES 3 ARGUMENTS:THE PORT NUMBER FROM 0 TO 3 AND POINTER TO VARIABLE
THAT WILL HOLD THE VALUE OF THE PORT AND RETURNS THE ERROR STATUS EITHER WRONG PORT NUMBER OR PASSING NULL 
POINTER AS AN ARGUMENT OR EVERY THING IS OK AND ASSIGNING THE PORT VALUE TO THE VARIABLE THAT WE HAVE PASSED
(CHECK THE OPTIONS ABOVE FOR THIS FUNCTION PARAMETERS TO BE ABLE TO USE THE API WITH A CORRECT BEHAVIOUR)*/
DIO_enumRetErrorState_t DIO_enumGetPortValue(u8 Copy_u8PortNumber,u8 *Copy_pu8PortValue);

#endif 